### ISSUE TITLE
Failed to build Forsaken libraries

### ISSUE THREAD

**Issue by hollanbeck** [ForsakenX/forsaken-libs#5]
I am following the guide to compile the Forsaken libraries as described in the wiki - https://github.com/ForsakenX/forsaken/wiki/Quick-and-easy-dev-setup so I try to compile all of the required libraries via the following line:

./libs/src/build.sh

and I get the following error:
...
+ cd zlib-1.2.5
+ ./configure --prefix=
Checking for gcc...
Please use win32/Makefile.gcc instead.
+ exit 1
Failed to build...

**Comment by chino** [comment]
Win32? Are you compiling for\on Windows? Would be helpful to see full output.

**Comment by hollanbeck** [comment]
I am compiling on Windows 7. I am attaching the build.log that contains the full output.
[build.log.txt](https://github.com/ForsakenX/forsaken-libs/files/1029573/build.log.txt)

**Comment by chino** [comment]
Are you using mingw or attempting to build using WSL? 

Note, I haven't had a Windows system in years.

I also never finished making this repo support mingw so you should try using the version that is dedicated for that.

See: https://github.com/ForsakenX/forsaken-libs-mingw32

I could add a link\note to the wiki and readme if that helps.

Try out that repo and open an issue there if needed.

May I ask, are you trying to fix a bug in Windows or possibly improve something?

**Comment by hollanbeck** [comment]
For now I am just rrying to build the project in Windows. When I do that and I take a look at the code I may have an adea about some improvements.

**Comment by chino** [comment]
Jump on IRC and talk to Silence or Lion. I hangout on slack as well which is easier for asynchronous chat.
